chg: Upgraded Terraform and AWS Provider
Upgraded to Terraform version 1.10 amd AWS provider version 5.0.
Input and output variables names have been changed, and also
resource names have changed.

BREAKING CHANGE

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,8 @@
 version: 2.1
 
 orbs:
-    vr: kohirens/version-release@3.1.0
+    vr: kohirens/version-release@4.3.0
+    aws-cli: circleci/aws-cli@5.1.2
 
 parameters:
     ctx_ci_cd:
@@ -19,24 +20,72 @@ parameters:
     ssh_finger:
         description: SSH fingerprint.
         type: string
-        default: "0c:23:b6:8c:c9:d0:e0:46:5e:ea:2e:39:f1:5f:7f:a4"
+        default: "SHA256:Qvx4ggu2U7cFb9ZznPsPkbv+XYoCas3vkoUVJ6AxnlE"
     triggered_flow:
         default: "workflow-selector"
         description: Workflow to be executed.
         type: string
+    aws_iac_role:
+        default: arn:aws:iam::755285156183:role/circleci-terraform-pipelines
+        description: CircleCI AWS IAC role.
+        type: string
 
-jobs:
-    run-test:
+executors:
+    terraform-exec:
         docker:
-            - image: hashicorp/terraform:1.6.3
+            - image: hashicorp/terraform:1.10.2
               auth:
                   username: ${DH_USER}
                   password: ${DH_PASS}
+
+commands:
+    aws-oidc-setup:
+        description: Setup AWS auth using OIDC token
+        parameters:
+            role_arn:
+                type: string
+            session_duration:
+                default: 900
+                type: integer
+        steps:
+            - run:
+                  name: Get AWS credentials
+                  command: |
+                      set -- $(aws sts assume-role-with-web-identity --role-arn << parameters.role_arn >> --role-session-name "${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}" --web-identity-token "${CIRCLE_OIDC_TOKEN}" --duration-seconds << parameters.session_duration >> --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text)
+                      aws_key="${1}" && shift
+                      aws_secret="${1}" && shift
+                      aws_token="${1}" && shift
+                      mkdir -p ~/.aws
+                      echo '[default]' > ~/.aws/credentials
+                      echo "aws_access_key_id=${aws_key}" >> ~/.aws/credentials
+                      echo "aws_secret_access_key=${aws_secret}" >> ~/.aws/credentials
+                      echo "aws_session_token=${aws_token}" >> ~/.aws/credentials
+                      if [ -f ~/.aws/credentials ]; then
+                          echo "credentials retrieved"
+                          exit 0
+                      fi
+                      echo "could not retrieve credentials"
+                      exit 1
+            - run:
+                  name: Verify AWS credentials
+                  command: |
+                      aws sts get-caller-identity
+
+jobs:
+    run-test:
+        executor: terraform-exec
+        environment:
+            AWS_DEFAULT_REGION: us-east-1
         steps:
             - checkout
             - run:
+                  name: Verify module formatting
                   command: terraform fmt -check -write=false -diff
+            - aws-cli/install
+            - aws-oidc-setup:
+                  role_arn: << pipeline.parameters.aws_iac_role >>
             - run:
+                  name: Run terraform test
                   command: |
                       terraform init
                       terraform validate
@@ -48,7 +97,6 @@ workflows:
             - run-test:
                   context:
                       - << pipeline.parameters.ctx_dockerhub >>
-                      - << pipeline.parameters.ctx_iac_test >>
                   filters: { branches: { ignore: /main|auto-update-changelog/ } }
 
     workflow-selector:
